<?php
/**
 * PurchaseOrderApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EConnectPsb\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EConnectPsb\ApiException;
use EConnectPsb\Configuration;
use EConnectPsb\HeaderSelector;
use EConnectPsb\ObjectSerializer;

/**
 * PurchaseOrderApi Class Doc Comment
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseOrderApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiV1PartyIdPurchaseOrderDocumentIdStatusGet' => [
            'application/json',
        ],
        'apiV1PartyIdPurchaseOrderQueryRecipientPartyPost' => [
            'application/json',
        ],
        'sendOrderCancellation' => [
            'application/json',
        ],
        'sendPurchaseOrder' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGet
     *
     * Get purchase order statuses.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\DocumentStatus[]
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGet($party_id, $document_id, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'][0])
    {
        list($response) = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo($party_id, $document_id, $contentType);
        return $response;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo
     *
     * Get purchase order statuses.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\DocumentStatus[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'][0])
    {
        $request = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\DocumentStatus[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\DocumentStatus[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\DocumentStatus[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\DocumentStatus[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\DocumentStatus[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsync
     *
     * Get purchase order statuses.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsync($party_id, $document_id, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'][0])
    {
        return $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo($party_id, $document_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo
     *
     * Get purchase order statuses.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetAsyncWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'][0])
    {
        $returnType = '\EConnectPsb\Model\DocumentStatus[]';
        $request = $this->apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1PartyIdPurchaseOrderDocumentIdStatusGetRequest($party_id, $document_id, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderDocumentIdStatusGet'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderDocumentIdStatusGet, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling apiV1PartyIdPurchaseOrderDocumentIdStatusGet'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderDocumentIdStatusGet, must be smaller than or equal to 256.');
        }
        

        $resourcePath = '/api/v1/{partyId}/purchaseOrder/{documentId}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPost
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnectPsb\Model\OrderDocumentFamily $document_family Document family (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EConnectPsb\Model\LookupParty
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPost($party_id, $request_body, $preferred_document_type_id = null, $document_family = null, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'][0])
    {
        list($response) = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $document_family, $contentType);
        return $response;
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnectPsb\Model\OrderDocumentFamily $document_family Document family (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EConnectPsb\Model\LookupParty, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, $document_family = null, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'][0])
    {
        $request = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id, $document_family, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\LookupParty' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\LookupParty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\LookupParty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\LookupParty';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\LookupParty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsync
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnectPsb\Model\OrderDocumentFamily $document_family Document family (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsync($party_id, $request_body, $preferred_document_type_id = null, $document_family = null, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'][0])
    {
        return $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $document_family, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo
     *
     * Lookup the recipient party (seller) for possible delivery.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnectPsb\Model\OrderDocumentFamily $document_family Document family (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, $document_family = null, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'][0])
    {
        $returnType = '\EConnectPsb\Model\LookupParty';
        $request = $this->apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id, $document_family, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  \EConnectPsb\Model\OrderDocumentFamily $document_family Document family (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiV1PartyIdPurchaseOrderQueryRecipientPartyPostRequest($party_id, $request_body, $preferred_document_type_id = null, $document_family = null, string $contentType = self::contentTypes['apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderQueryRecipientPartyPost, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'request_body' is set
        if ($request_body === null || (is_array($request_body) && count($request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_body when calling apiV1PartyIdPurchaseOrderQueryRecipientPartyPost'
            );
        }

        if ($preferred_document_type_id !== null && !preg_match("/[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/", $preferred_document_type_id)) {
            throw new \InvalidArgumentException("invalid value for \"preferred_document_type_id\" when calling PurchaseOrderApi.apiV1PartyIdPurchaseOrderQueryRecipientPartyPost, must conform to the pattern /[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/.");
        }
        


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/queryRecipientParty';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $preferred_document_type_id,
            'preferredDocumentTypeId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $document_family,
            'documentFamily', // param base name
            'OrderDocumentFamily', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request_body));
            } else {
                $httpBody = $request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendOrderCancellation
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnectPsb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOrderCancellation'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\Document
     */
    public function sendOrderCancellation($party_id, $document_id, $order_cancellation, string $contentType = self::contentTypes['sendOrderCancellation'][0])
    {
        list($response) = $this->sendOrderCancellationWithHttpInfo($party_id, $document_id, $order_cancellation, $contentType);
        return $response;
    }

    /**
     * Operation sendOrderCancellationWithHttpInfo
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnectPsb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOrderCancellation'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendOrderCancellationWithHttpInfo($party_id, $document_id, $order_cancellation, string $contentType = self::contentTypes['sendOrderCancellation'][0])
    {
        $request = $this->sendOrderCancellationRequest($party_id, $document_id, $order_cancellation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\Document' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendOrderCancellationAsync
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnectPsb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOrderCancellation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendOrderCancellationAsync($party_id, $document_id, $order_cancellation, string $contentType = self::contentTypes['sendOrderCancellation'][0])
    {
        return $this->sendOrderCancellationAsyncWithHttpInfo($party_id, $document_id, $order_cancellation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendOrderCancellationAsyncWithHttpInfo
     *
     * Send order cancellation to let the seller know the order is cancelled.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnectPsb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOrderCancellation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendOrderCancellationAsyncWithHttpInfo($party_id, $document_id, $order_cancellation, string $contentType = self::contentTypes['sendOrderCancellation'][0])
    {
        $returnType = '\EConnectPsb\Model\Document';
        $request = $this->sendOrderCancellationRequest($party_id, $document_id, $order_cancellation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendOrderCancellation'
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the cancellation is about. (required)
     * @param  \EConnectPsb\Model\OrderCancellation $order_cancellation Order cancellation message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendOrderCancellation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendOrderCancellationRequest($party_id, $document_id, $order_cancellation, string $contentType = self::contentTypes['sendOrderCancellation'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling sendOrderCancellation'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.sendOrderCancellation, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling sendOrderCancellation'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseOrderApi.sendOrderCancellation, must be smaller than or equal to 256.');
        }
        
        // verify the required parameter 'order_cancellation' is set
        if ($order_cancellation === null || (is_array($order_cancellation) && count($order_cancellation) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_cancellation when calling sendOrderCancellation'
            );
        }


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/{documentId}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($order_cancellation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($order_cancellation));
            } else {
                $httpBody = $order_cancellation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendPurchaseOrder
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendPurchaseOrder'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\Document
     */
    public function sendPurchaseOrder($party_id, $file, $receiver_id = null, $channel = null, string $contentType = self::contentTypes['sendPurchaseOrder'][0])
    {
        list($response) = $this->sendPurchaseOrderWithHttpInfo($party_id, $file, $receiver_id, $channel, $contentType);
        return $response;
    }

    /**
     * Operation sendPurchaseOrderWithHttpInfo
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendPurchaseOrder'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendPurchaseOrderWithHttpInfo($party_id, $file, $receiver_id = null, $channel = null, string $contentType = self::contentTypes['sendPurchaseOrder'][0])
    {
        $request = $this->sendPurchaseOrderRequest($party_id, $file, $receiver_id, $channel, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\Document' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendPurchaseOrderAsync
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendPurchaseOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendPurchaseOrderAsync($party_id, $file, $receiver_id = null, $channel = null, string $contentType = self::contentTypes['sendPurchaseOrder'][0])
    {
        return $this->sendPurchaseOrderAsyncWithHttpInfo($party_id, $file, $receiver_id, $channel, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendPurchaseOrderAsyncWithHttpInfo
     *
     * Send a purchase order.
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendPurchaseOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendPurchaseOrderAsyncWithHttpInfo($party_id, $file, $receiver_id = null, $channel = null, string $contentType = self::contentTypes['sendPurchaseOrder'][0])
    {
        $returnType = '\EConnectPsb\Model\Document';
        $request = $this->sendPurchaseOrderRequest($party_id, $file, $receiver_id, $channel, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendPurchaseOrder'
     *
     * @param  string $party_id The sender (buyer) partyId. (required)
     * @param  \SplFileObject $file Multipart file upload. (required)
     * @param  string $receiver_id An optional receiver partyId to enforce delivery to a specific endpoint. The receiverId will be injected into the document. (optional)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendPurchaseOrder'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendPurchaseOrderRequest($party_id, $file, $receiver_id = null, $channel = null, string $contentType = self::contentTypes['sendPurchaseOrder'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling sendPurchaseOrder'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseOrderApi.sendPurchaseOrder, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling sendPurchaseOrder'
            );
        }

        if ($receiver_id !== null && !preg_match("/[A-Za-z0-9-=:]+/", $receiver_id)) {
            throw new \InvalidArgumentException("invalid value for \"receiver_id\" when calling PurchaseOrderApi.sendPurchaseOrder, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        


        $resourcePath = '/api/v1/{partyId}/purchaseOrder/send';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $receiver_id,
            'receiverId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channel,
            'channel', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
