<?php
/**
 * PurchaseInvoiceApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EConnectPsb\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EConnectPsb\ApiException;
use EConnectPsb\Configuration;
use EConnectPsb\HeaderSelector;
use EConnectPsb\ObjectSerializer;

/**
 * PurchaseInvoiceApi Class Doc Comment
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseInvoiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deletePurchaseInvoice' => [
            'application/json',
        ],
        'downloadPurchaseInvoice' => [
            'application/json',
        ],
        'getPurchaseInvoiceStatuses' => [
            'application/json',
        ],
        'queryRecipientPartyForInvoiceResponse' => [
            'application/json',
        ],
        'recognizePurchaseInvoice' => [
            'multipart/form-data',
        ],
        'sendInvoiceResponse' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deletePurchaseInvoice
     *
     * Delete purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  string $document_id The service bus documentId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deletePurchaseInvoice($party_id, $document_id, string $contentType = self::contentTypes['deletePurchaseInvoice'][0])
    {
        $this->deletePurchaseInvoiceWithHttpInfo($party_id, $document_id, $contentType);
    }

    /**
     * Operation deletePurchaseInvoiceWithHttpInfo
     *
     * Delete purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  string $document_id The service bus documentId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deletePurchaseInvoiceWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['deletePurchaseInvoice'][0])
    {
        $request = $this->deletePurchaseInvoiceRequest($party_id, $document_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deletePurchaseInvoiceAsync
     *
     * Delete purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  string $document_id The service bus documentId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePurchaseInvoiceAsync($party_id, $document_id, string $contentType = self::contentTypes['deletePurchaseInvoice'][0])
    {
        return $this->deletePurchaseInvoiceAsyncWithHttpInfo($party_id, $document_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deletePurchaseInvoiceAsyncWithHttpInfo
     *
     * Delete purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  string $document_id The service bus documentId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePurchaseInvoiceAsyncWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['deletePurchaseInvoice'][0])
    {
        $returnType = '';
        $request = $this->deletePurchaseInvoiceRequest($party_id, $document_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deletePurchaseInvoice'
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  string $document_id The service bus documentId (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deletePurchaseInvoiceRequest($party_id, $document_id, string $contentType = self::contentTypes['deletePurchaseInvoice'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling deletePurchaseInvoice'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.deletePurchaseInvoice, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling deletePurchaseInvoice'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseInvoiceApi.deletePurchaseInvoice, must be smaller than or equal to 256.');
        }
        

        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/{documentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation downloadPurchaseInvoice
     *
     * Download purchase invoice.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $target_format The target format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadPurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\SplFileObject
     */
    public function downloadPurchaseInvoice($party_id, $document_id, $target_format = null, string $contentType = self::contentTypes['downloadPurchaseInvoice'][0])
    {
        list($response) = $this->downloadPurchaseInvoiceWithHttpInfo($party_id, $document_id, $target_format, $contentType);
        return $response;
    }

    /**
     * Operation downloadPurchaseInvoiceWithHttpInfo
     *
     * Download purchase invoice.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $target_format The target format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadPurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function downloadPurchaseInvoiceWithHttpInfo($party_id, $document_id, $target_format = null, string $contentType = self::contentTypes['downloadPurchaseInvoice'][0])
    {
        $request = $this->downloadPurchaseInvoiceRequest($party_id, $document_id, $target_format, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\SplFileObject' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SplFileObject' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SplFileObject', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SplFileObject';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation downloadPurchaseInvoiceAsync
     *
     * Download purchase invoice.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $target_format The target format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadPurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadPurchaseInvoiceAsync($party_id, $document_id, $target_format = null, string $contentType = self::contentTypes['downloadPurchaseInvoice'][0])
    {
        return $this->downloadPurchaseInvoiceAsyncWithHttpInfo($party_id, $document_id, $target_format, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation downloadPurchaseInvoiceAsyncWithHttpInfo
     *
     * Download purchase invoice.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $target_format The target format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadPurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadPurchaseInvoiceAsyncWithHttpInfo($party_id, $document_id, $target_format = null, string $contentType = self::contentTypes['downloadPurchaseInvoice'][0])
    {
        $returnType = '\SplFileObject';
        $request = $this->downloadPurchaseInvoiceRequest($party_id, $document_id, $target_format, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'downloadPurchaseInvoice'
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $target_format The target format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['downloadPurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function downloadPurchaseInvoiceRequest($party_id, $document_id, $target_format = null, string $contentType = self::contentTypes['downloadPurchaseInvoice'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling downloadPurchaseInvoice'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.downloadPurchaseInvoice, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling downloadPurchaseInvoice'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseInvoiceApi.downloadPurchaseInvoice, must be smaller than or equal to 256.');
        }
        
        if ($target_format !== null && !preg_match("/[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/", $target_format)) {
            throw new \InvalidArgumentException("invalid value for \"target_format\" when calling PurchaseInvoiceApi.downloadPurchaseInvoice, must conform to the pattern /[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/.");
        }
        

        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/{documentId}/download';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $target_format,
            'targetFormat', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPurchaseInvoiceStatuses
     *
     * Get purchase invoice statuses.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPurchaseInvoiceStatuses'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\DocumentStatus[]
     */
    public function getPurchaseInvoiceStatuses($party_id, $document_id, string $contentType = self::contentTypes['getPurchaseInvoiceStatuses'][0])
    {
        list($response) = $this->getPurchaseInvoiceStatusesWithHttpInfo($party_id, $document_id, $contentType);
        return $response;
    }

    /**
     * Operation getPurchaseInvoiceStatusesWithHttpInfo
     *
     * Get purchase invoice statuses.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPurchaseInvoiceStatuses'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\DocumentStatus[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getPurchaseInvoiceStatusesWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['getPurchaseInvoiceStatuses'][0])
    {
        $request = $this->getPurchaseInvoiceStatusesRequest($party_id, $document_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\DocumentStatus[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\DocumentStatus[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\DocumentStatus[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\DocumentStatus[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\DocumentStatus[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPurchaseInvoiceStatusesAsync
     *
     * Get purchase invoice statuses.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPurchaseInvoiceStatuses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPurchaseInvoiceStatusesAsync($party_id, $document_id, string $contentType = self::contentTypes['getPurchaseInvoiceStatuses'][0])
    {
        return $this->getPurchaseInvoiceStatusesAsyncWithHttpInfo($party_id, $document_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPurchaseInvoiceStatusesAsyncWithHttpInfo
     *
     * Get purchase invoice statuses.
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPurchaseInvoiceStatuses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPurchaseInvoiceStatusesAsyncWithHttpInfo($party_id, $document_id, string $contentType = self::contentTypes['getPurchaseInvoiceStatuses'][0])
    {
        $returnType = '\EConnectPsb\Model\DocumentStatus[]';
        $request = $this->getPurchaseInvoiceStatusesRequest($party_id, $document_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPurchaseInvoiceStatuses'
     *
     * @param  string $party_id The recipient partyId. (required)
     * @param  string $document_id The service bus documentId. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPurchaseInvoiceStatuses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPurchaseInvoiceStatusesRequest($party_id, $document_id, string $contentType = self::contentTypes['getPurchaseInvoiceStatuses'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling getPurchaseInvoiceStatuses'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.getPurchaseInvoiceStatuses, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling getPurchaseInvoiceStatuses'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseInvoiceApi.getPurchaseInvoiceStatuses, must be smaller than or equal to 256.');
        }
        

        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/{documentId}/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation queryRecipientPartyForInvoiceResponse
     *
     * Lookup the recipient party (seller/supplier) for possible delivery.
     *
     * @param  string $party_id The sender (buyer/customer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['queryRecipientPartyForInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EConnectPsb\Model\LookupParty
     */
    public function queryRecipientPartyForInvoiceResponse($party_id, $request_body, $preferred_document_type_id = null, string $contentType = self::contentTypes['queryRecipientPartyForInvoiceResponse'][0])
    {
        list($response) = $this->queryRecipientPartyForInvoiceResponseWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $contentType);
        return $response;
    }

    /**
     * Operation queryRecipientPartyForInvoiceResponseWithHttpInfo
     *
     * Lookup the recipient party (seller/supplier) for possible delivery.
     *
     * @param  string $party_id The sender (buyer/customer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['queryRecipientPartyForInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EConnectPsb\Model\LookupParty, HTTP status code, HTTP response headers (array of strings)
     */
    public function queryRecipientPartyForInvoiceResponseWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, string $contentType = self::contentTypes['queryRecipientPartyForInvoiceResponse'][0])
    {
        $request = $this->queryRecipientPartyForInvoiceResponseRequest($party_id, $request_body, $preferred_document_type_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\LookupParty' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\LookupParty' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\LookupParty', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\LookupParty';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\LookupParty',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation queryRecipientPartyForInvoiceResponseAsync
     *
     * Lookup the recipient party (seller/supplier) for possible delivery.
     *
     * @param  string $party_id The sender (buyer/customer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['queryRecipientPartyForInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function queryRecipientPartyForInvoiceResponseAsync($party_id, $request_body, $preferred_document_type_id = null, string $contentType = self::contentTypes['queryRecipientPartyForInvoiceResponse'][0])
    {
        return $this->queryRecipientPartyForInvoiceResponseAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation queryRecipientPartyForInvoiceResponseAsyncWithHttpInfo
     *
     * Lookup the recipient party (seller/supplier) for possible delivery.
     *
     * @param  string $party_id The sender (buyer/customer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['queryRecipientPartyForInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function queryRecipientPartyForInvoiceResponseAsyncWithHttpInfo($party_id, $request_body, $preferred_document_type_id = null, string $contentType = self::contentTypes['queryRecipientPartyForInvoiceResponse'][0])
    {
        $returnType = '\EConnectPsb\Model\LookupParty';
        $request = $this->queryRecipientPartyForInvoiceResponseRequest($party_id, $request_body, $preferred_document_type_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'queryRecipientPartyForInvoiceResponse'
     *
     * @param  string $party_id The sender (buyer/customer) partyId. (required)
     * @param  string[] $request_body All possible partyIds of the recipient party. (required)
     * @param  string $preferred_document_type_id The source or preferred documentTypeId to match with and to determine the partyId format. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['queryRecipientPartyForInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function queryRecipientPartyForInvoiceResponseRequest($party_id, $request_body, $preferred_document_type_id = null, string $contentType = self::contentTypes['queryRecipientPartyForInvoiceResponse'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling queryRecipientPartyForInvoiceResponse'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.queryRecipientPartyForInvoiceResponse, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'request_body' is set
        if ($request_body === null || (is_array($request_body) && count($request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_body when calling queryRecipientPartyForInvoiceResponse'
            );
        }

        if ($preferred_document_type_id !== null && !preg_match("/[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/", $preferred_document_type_id)) {
            throw new \InvalidArgumentException("invalid value for \"preferred_document_type_id\" when calling PurchaseInvoiceApi.queryRecipientPartyForInvoiceResponse, must conform to the pattern /[A-Za-z0-9-:.]{1,}[#]{2}[A-Za-z0-9-:.#*]{1,}|^$/.");
        }
        

        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/queryRecipientParty';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $preferred_document_type_id,
            'preferredDocumentTypeId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request_body));
            } else {
                $httpBody = $request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation recognizePurchaseInvoice
     *
     * Recognize purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  \SplFileObject $file The service bus documentId (required)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recognizePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\Document
     */
    public function recognizePurchaseInvoice($party_id, $file, $channel = null, string $contentType = self::contentTypes['recognizePurchaseInvoice'][0])
    {
        list($response) = $this->recognizePurchaseInvoiceWithHttpInfo($party_id, $file, $channel, $contentType);
        return $response;
    }

    /**
     * Operation recognizePurchaseInvoiceWithHttpInfo
     *
     * Recognize purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  \SplFileObject $file The service bus documentId (required)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recognizePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function recognizePurchaseInvoiceWithHttpInfo($party_id, $file, $channel = null, string $contentType = self::contentTypes['recognizePurchaseInvoice'][0])
    {
        $request = $this->recognizePurchaseInvoiceRequest($party_id, $file, $channel, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\Document' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation recognizePurchaseInvoiceAsync
     *
     * Recognize purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  \SplFileObject $file The service bus documentId (required)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recognizePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recognizePurchaseInvoiceAsync($party_id, $file, $channel = null, string $contentType = self::contentTypes['recognizePurchaseInvoice'][0])
    {
        return $this->recognizePurchaseInvoiceAsyncWithHttpInfo($party_id, $file, $channel, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation recognizePurchaseInvoiceAsyncWithHttpInfo
     *
     * Recognize purchase invoice.
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  \SplFileObject $file The service bus documentId (required)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recognizePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function recognizePurchaseInvoiceAsyncWithHttpInfo($party_id, $file, $channel = null, string $contentType = self::contentTypes['recognizePurchaseInvoice'][0])
    {
        $returnType = '\EConnectPsb\Model\Document';
        $request = $this->recognizePurchaseInvoiceRequest($party_id, $file, $channel, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'recognizePurchaseInvoice'
     *
     * @param  string $party_id The recipient partyId (required)
     * @param  \SplFileObject $file The service bus documentId (required)
     * @param  string $channel An optional parameter to enforce the use of a delivery channel. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['recognizePurchaseInvoice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function recognizePurchaseInvoiceRequest($party_id, $file, $channel = null, string $contentType = self::contentTypes['recognizePurchaseInvoice'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling recognizePurchaseInvoice'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.recognizePurchaseInvoice, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling recognizePurchaseInvoice'
            );
        }



        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/recognize';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channel,
            'channel', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendInvoiceResponse
     *
     * Send invoice response to let the seller know the status of the received invoice.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the response is about. (required)
     * @param  \EConnectPsb\Model\InvoiceResponse $invoice_response Invoice response message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return |\EConnectPsb\Model\Document
     */
    public function sendInvoiceResponse($party_id, $document_id, $invoice_response, string $contentType = self::contentTypes['sendInvoiceResponse'][0])
    {
        list($response) = $this->sendInvoiceResponseWithHttpInfo($party_id, $document_id, $invoice_response, $contentType);
        return $response;
    }

    /**
     * Operation sendInvoiceResponseWithHttpInfo
     *
     * Send invoice response to let the seller know the status of the received invoice.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the response is about. (required)
     * @param  \EConnectPsb\Model\InvoiceResponse $invoice_response Invoice response message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \EConnectPsb\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of |\EConnectPsb\Model\Document, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendInvoiceResponseWithHttpInfo($party_id, $document_id, $invoice_response, string $contentType = self::contentTypes['sendInvoiceResponse'][0])
    {
        $request = $this->sendInvoiceResponseRequest($party_id, $document_id, $invoice_response, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\EConnectPsb\Model\Document' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EConnectPsb\Model\Document' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EConnectPsb\Model\Document', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\EConnectPsb\Model\Document';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EConnectPsb\Model\Document',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendInvoiceResponseAsync
     *
     * Send invoice response to let the seller know the status of the received invoice.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the response is about. (required)
     * @param  \EConnectPsb\Model\InvoiceResponse $invoice_response Invoice response message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendInvoiceResponseAsync($party_id, $document_id, $invoice_response, string $contentType = self::contentTypes['sendInvoiceResponse'][0])
    {
        return $this->sendInvoiceResponseAsyncWithHttpInfo($party_id, $document_id, $invoice_response, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendInvoiceResponseAsyncWithHttpInfo
     *
     * Send invoice response to let the seller know the status of the received invoice.
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the response is about. (required)
     * @param  \EConnectPsb\Model\InvoiceResponse $invoice_response Invoice response message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendInvoiceResponseAsyncWithHttpInfo($party_id, $document_id, $invoice_response, string $contentType = self::contentTypes['sendInvoiceResponse'][0])
    {
        $returnType = '\EConnectPsb\Model\Document';
        $request = $this->sendInvoiceResponseRequest($party_id, $document_id, $invoice_response, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendInvoiceResponse'
     *
     * @param  string $party_id Your partyId (buyer). (required)
     * @param  string $document_id DocumentId that the response is about. (required)
     * @param  \EConnectPsb\Model\InvoiceResponse $invoice_response Invoice response message. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['sendInvoiceResponse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function sendInvoiceResponseRequest($party_id, $document_id, $invoice_response, string $contentType = self::contentTypes['sendInvoiceResponse'][0])
    {

        // verify the required parameter 'party_id' is set
        if ($party_id === null || (is_array($party_id) && count($party_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $party_id when calling sendInvoiceResponse'
            );
        }
        if (!preg_match("/[A-Za-z0-9-=:]+/", $party_id)) {
            throw new \InvalidArgumentException("invalid value for \"party_id\" when calling PurchaseInvoiceApi.sendInvoiceResponse, must conform to the pattern /[A-Za-z0-9-=:]+/.");
        }
        
        // verify the required parameter 'document_id' is set
        if ($document_id === null || (is_array($document_id) && count($document_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $document_id when calling sendInvoiceResponse'
            );
        }
        if (strlen($document_id) > 256) {
            throw new \InvalidArgumentException('invalid length for "$document_id" when calling PurchaseInvoiceApi.sendInvoiceResponse, must be smaller than or equal to 256.');
        }
        
        // verify the required parameter 'invoice_response' is set
        if ($invoice_response === null || (is_array($invoice_response) && count($invoice_response) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $invoice_response when calling sendInvoiceResponse'
            );
        }


        $resourcePath = '/api/v1/{partyId}/purchaseInvoice/{documentId}/response';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($party_id !== null) {
            $resourcePath = str_replace(
                '{' . 'partyId' . '}',
                ObjectSerializer::toPathValue($party_id),
                $resourcePath
            );
        }
        // path params
        if ($document_id !== null) {
            $resourcePath = str_replace(
                '{' . 'documentId' . '}',
                ObjectSerializer::toPathValue($document_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($invoice_response)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($invoice_response));
            } else {
                $httpBody = $invoice_response;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Subscription-Key');
        if ($apiKey !== null) {
            $headers['Subscription-Key'] = $apiKey;
        }
        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
