<?php
/**
 * PurchaseOrderApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EConnect\Psb\Test\Api;

use \EConnect\Psb\Configuration;
use \EConnect\Psb\ApiException;
use \EConnect\Psb\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PurchaseOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  EConnect\Psb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PurchaseOrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1PartyIdPurchaseOrderDocumentIdStatusGet
     *
     * Get purchase order statuses..
     *
     */
    public function testApiV1PartyIdPurchaseOrderDocumentIdStatusGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PartyIdPurchaseOrderQueryRecipientPartyPost
     *
     * Lookup the recipient party (seller) for possible delivery..
     *
     */
    public function testApiV1PartyIdPurchaseOrderQueryRecipientPartyPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendOrderCancellation
     *
     * Send order cancellation to let the seller know the order is cancelled..
     *
     */
    public function testSendOrderCancellation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendPurchaseOrder
     *
     * Send a purchase order..
     *
     */
    public function testSendPurchaseOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
