<?php
/**
 * SalesOrderApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PSB API 1.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: techsupport@econnect.eu
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EConnectPsb\Test\Api;

use \EConnectPsb\Configuration;
use \EConnectPsb\ApiException;
use \EConnectPsb\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  EConnectPsb
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesOrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSalesOrder
     *
     * Delete sales order..
     *
     */
    public function testDeleteSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadSalesOrder
     *
     * Download sales order..
     *
     */
    public function testDownloadSalesOrder()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSalesOrderStatuses
     *
     * Get sales order statuses..
     *
     */
    public function testGetSalesOrderStatuses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queryRecipientPartyForOrderResponse
     *
     * Lookup the recipient party (buyer/customer) for possible delivery..
     *
     */
    public function testQueryRecipientPartyForOrderResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendOrderResponse
     *
     * Send order response to let the buyer know the status of the received order..
     *
     */
    public function testSendOrderResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
